name: Microservices Continuous Deployment with Github Actions

on:
  push:
    branches:
    - "main"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_ACCESS_TOKEN}}

    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'

#    - name: Build Eureka Naming Server Docker Image
#      working-directory: ./19_MicroservicesRunningInKubernetesCluster/naming-server
#      run: mvn spring-boot:build-image
#
#    - name: Build API Gateway Docker Image
#      working-directory: ./19_MicroservicesRunningInKubernetesCluster/api-gateway
#      run: mvn spring-boot:build-image

    - name: Build Exchange Microservice Docker Image
      working-directory: ./19_MicroservicesRunningInKubernetesCluster/exchange-service
      run: mvn clean package

    - name: Build Book Microservice Docker Image
      working-directory: ./19_MicroservicesRunningInKubernetesCluster/book-service
      run: mvn clean package

    - name: Docker Compose Build
      working-directory: ./19_MicroservicesRunningInKubernetesCluster
      run: docker compose build

    - name: Tag Docker Images
      run: |
        docker tag ${{secrets.DOCKER_USERNAME}}/book-service:latest ${{secrets.DOCKER_USERNAME}}/book-service:${{github.RUN_ID}}
        docker tag ${{secrets.DOCKER_USERNAME}}/book-service:latest ${{secrets.DOCKER_USERNAME}}/book-service:kube-v1
        docker tag ${{secrets.DOCKER_USERNAME}}/exchange-service:latest ${{secrets.DOCKER_USERNAME}}/exchange-service:${{github.RUN_ID}}
        docker tag ${{secrets.DOCKER_USERNAME}}/exchange-service:latest ${{secrets.DOCKER_USERNAME}}/exchange-service:kube-v1
      

    - name: Push Docker Images to Docker Hub
      run: |
        docker push ${{secrets.DOCKER_USERNAME}}/book-service:latest
        docker push ${{secrets.DOCKER_USERNAME}}/book-service:kube-v1
        docker push ${{secrets.DOCKER_USERNAME}}/book-service:${{github.RUN_ID}}
        docker push ${{secrets.DOCKER_USERNAME}}/exchange-service:latest
        docker push ${{secrets.DOCKER_USERNAME}}/exchange-service:kube-v1
        docker push ${{secrets.DOCKER_USERNAME}}/exchange-service:${{github.RUN_ID}}