name: Microservices Continuous Deployment with Github Actions

on:
  push:
    branches:
    - "main"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_ACCESS_TOKEN}}

    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Build Eureka Naming Server Docker Image
      working-directory: ./16_CIandCDwithGithubActionsandDockerHub/naming-server
      run: mvn spring-boot:build-image -DskipTests